FROM python:slim
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
ADD src/ /
RUN pip install pysolar requests
RUN pip install gpiozero --break-system-packages
CMD ["python", "main.py"]
